version: "3"
services:
    backend:
        image: django-slack:latest
        container_name: django-app
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - "8000:8000"
    fronend:
        image: react-front:latest
        container_name: react-app
        ports:
            - "3000:3000"
        stdin_open: true
        tty: true
